### PR TITLE
Fix compile

### PR DESCRIPTION
**Pull request by mirh**
Misplaced parenthesis

### CODE REVIEW

**Review by lukeiwanski — APPROVED** [review]
Thanks! Don't use this branch yet as I am working on fixing few things for it. :)

**Comment by mirh** [comment]
> Don't use this branch yet as I am working on fixing few things for it. :)

As if instead the other branches worked for me /s

**Comment by lukeiwanski** [comment]
What error do you see on the dev/amd_gpu?

Is that still the crash when queuing devices?

**Comment by mirh** [comment]
Yep, the usual #205.

**Pull request merged**
